### ISSUE TITLE
[FEATURE] Peacefully coexist with Laravel-Debugbar

### ISSUE THREAD

**Issue by mikeerickson** [daylerees/anbu#12]
So, when both of these tools are enabled (there are some unique features in both) Anbu is stepping on the toes of Laravel-Debugbar (or vise versa).   I will cross post this on Laravel-Debugbar (maybe you two chaps can work together to make it happen)

**Comment by daylerees** [comment]
What bugs are happening?

**Comment by mikeerickson** [comment]
During redirect, it displays a "redirecting to ...." message

**Comment by daylerees** [comment]
This is just a matter of understanding that tools that do a similar thing may collide.

**Comment by mikeerickson** [comment]
Dayle -

So, shall I interrupt this as you saying you don't have an interest in coexisting with Debugbar and I need to chose between the two?

Just trying to get a clear statement and my assumptions are based on fact that you have closed this issue

**Comment by barryvdh** [comment]
If you make a test case we could probably fix it, but still they both probably do much the same, so not sure how useful running both the same time is..

**Comment by daylerees** [comment]
I think the majority will run just one, but making them cooperate would mean one of us moving content from the bottom of the screen. I could lift the badge by `32px` but then it would be floating for those not using debugbar, I could move the badge to the top of the screen, but normally that collides with menus (prime real estate). That or I could seek for debugbar being loaded, and only lift the badge in that instance. It's possible, but where to I draw the line. Barry's and mine aren't the only PHP profilers, so I'd have to move the badge around to dodge all :)

**Comment by barryvdh** [comment]
I wouldn't make exceptions like that. 
But is this still about the badge location (because anbu doesn't need it to function) or about redirects not working? If so, please provide an example.

**Comment by daylerees** [comment]
Laravel used to have a 'Redirecting to...' body for Redirect::to responses (for if the browser didn't handle the 302 correctly). Sounds like it could be that.

**Comment by barryvdh** [comment]
Yeah it was, but that didn't have anything to do with my debugbar I think, just that Anbu didn't properly handle redirects. Submitted a patch in #15

**Comment by barryvdh** [comment]
And for the rest, they don't seem to conflict, other then Anbu listening to Debugbar asset/openhandler requests and Debugbar listening to Anbu calls, but that's not a real problem. But if you are missing anything from both I would suggest you make a PR for that, both should be able to provide the same functionality, it would be a bit weird of you needed both (I think, haven't looked at Anbu so much yet)
