### ISSUE TITLE
Laravel 5

### ISSUE THREAD

**Issue by garygreen** [daylerees/anbu#33]
Any plans Dayle? :smile:

**Comment by andrewhood125** [comment]
:+1: Is there anything else out there like anbu for L5?

**Comment by barryvdh** [comment]
https://github.com/itsgoingd/clockwork
https://github.com/barryvdh/laravel-debugbar

**Comment by garygreen** [comment]
I've submitted a PR for this if anyone is interested and want's to test. #35
