### ISSUE TITLE
Very slow on load any page from laravel projetct

### ISSUE THREAD

**Issue by faytzel** [daylerees/anbu#6]
Hello.
When i enabled Anbu the page request delayed 50 seconds approximately.
But when i disabled Anbu delayed less than 1 second approximately.

Note: The "storage" field on "anbu" table weighs about 10 kb approximately.

**Comment by Freyskeyd** [comment]
Too many log?
Log database query?

**Comment by faytzel** [comment]
I found the problem, the package Rocketeer (http://rocketeer.autopergamene.eu) becomes very slow petitions, when I remove Rocketeer Service Provider in app/config/app.php the http requests running normally in the project.

In Anbu Container Bindings:
![container___anbu](https://cloud.githubusercontent.com/assets/1248446/4189006/07aeeba0-3778-11e4-88a6-8029e7b29e69.png)

**Comment by daylerees** [comment]
That's the container debug module. It resolves things in the container to test their resolution time. Not sure why that one takes so long, but I'm considering making that module optional (for other reasons).

**Comment by daylerees** [comment]
With the container section removed for now, an update should stop this.

**Comment by faytzel** [comment]
I understand. Now everything works fine. Very thanks :)
